### ISSUE TITLE
Organize helpers directory

### ISSUE THREAD

**Issue by nessthehero** [BarkleyREI/sass_boilerplate#22]
Ideas:
- Split _common.scss into a directory with multiple files
  - placeholder styles
  - content class styles
  - opinionated REI reset styles

README to help explain things like color-pallette, mixins, etc.

**Comment by JDillon522** [comment]
Probably a good idea. Even if nobody really ever touches anything in there it will make it more logical to follow and maintain.

Weee for abstraction
